### ISSUE TITLE
Arch Linux Go Err

### ISSUE THREAD

**Issue by curtisrecords** [Mikubill/nali-go#1]
goroutine 1 [running]:
github.com/zu1k/nali/pkg/zxipv6wry.Un7z({0xc000024880?, 0xc0004d1140?})
        github.com/zu1k/nali/pkg/zxipv6wry/update.go:56 +0x4d7
github.com/zu1k/nali/pkg/zxipv6wry.getData()
        github.com/zu1k/nali/pkg/zxipv6wry/update.go:48 +0x276
github.com/zu1k/nali/pkg/zxipv6wry.Download({0xc0001cf140, 0x1c})
        github.com/zu1k/nali/pkg/zxipv6wry/update.go:15 +0x2d
github.com/zu1k/nali/cmd.glob..func2(0x560a7f0be1c0?, {0x560a7ed954b6?, 0x0?, 0x0?})
        github.com/zu1k/nali/cmd/update.go:32 +0x174
github.com/spf13/cobra.(*Command).execute(0x560a7f0be1c0, {0x560a7f1433b8, 0x0, 0x0})
        github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x560a7f0bdf40)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
github.com/zu1k/nali/cmd.Execute()
        github.com/zu1k/nali/cmd/root.go:64 +0x25
main.main()
        github.com/zu1k/nali/main.go:8 +0x17

**Comment by curtisrecords** [comment]
环境
```bash
                   -`
                  .o+`                 curtis@Curtis-Records-ITX
                 `ooo/                 OS: Arch Linux (on the Windows Subsystem for Linux)
                `+oooo:                Kernel: x86_64 Linux 5.10.60.1-microsoft-standard-WSL2
               `+oooooo:               Uptime: 1d 2h 6m
               -+oooooo+:              Packages: 484
             `/:-:++oooo+:             Shell: zsh 5.8.1
            `/++++/+++++++:            Resolution: 1920x1080
           `/++++++++++++++:           WM: Weston WM
          `/+++ooooooooooooo/`         GTK Theme: Adwaita [GTK3]
         ./ooosssso++osssssso+`        Disk: 2.8T / 5.6T (50%)
        .oossssso-````/ossssss+`       CPU: Intel Core i7-10700 @ 16x 2.904GHz
       -osssssso.      :ssssssso.      GPU: NVIDIA GeForce GTX 1660 SUPER
      :osssssss/        osssso+++.     RAM: 1731MiB / 7906MiB
     /ossssssss/        +ssssooo/-
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
```
